coverage:
  status:
    project:
      backend:
        flags:
          - backend
      frontend:
        flags:
          - frontend

flags:
  backend:
    carryforward: true
  frontend:
    carryforward: true
