services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - dev-static-data:/vol/web
    command:  >
      sh -c "echo 'Waiting for db...' &&
             wait-for-it --service db:5432 --timeout 60 &&
             echo 'DB is ready.' && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=pass
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17-bookworm
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=pass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "devdb", "-U", "devuser"]

  frontend:
    build:
      context: ./frontend
      args:
        - DEV=true
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    command:
      sh -c "npm run dev -- --host=0.0.0.0 --port 5173"

volumes:
  dev-db-data:
  dev-static-data:
