# Generated by Django 5.2.9 on 2026-01-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_user_is_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_guest', 'date_joined'], name='user_user_is_gues_4b2a44_idx'),
        ),
    ]
