# Generated by Django 5.2.7 on 2025-10-23 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_board_title_per_user'),
        ),
    ]
