# Generated by Django 5.2.7 on 2025-10-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_column'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('board', 'title'), name='unique_column_title_per_board'),
        ),
    ]
