# Generated by Django 5.2.7 on 2025-10-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_column_unique_column_title_per_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
