# Generated by Django 5.2.9 on 2025-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
