# Generated by Django 5.2.9 on 2026-01-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_starred'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_board_title_per_user',
        ),
    ]
