# Generated by Django 5.2.9 on 2026-01-14 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_board_unique_board_title_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['user_id', 'is_default', 'created_at', 'updated_at'], name='board_board_user_id_0181b2_idx'),
        ),
    ]
