# Generated by Django 5.2.9 on 2026-01-14 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_board_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='board',
            name='board_board_user_id_0181b2_idx',
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['user', 'is_default'], name='board_user_default_idx'),
        ),
    ]
