# Generated by Django 5.2.7 on 2025-11-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
