# Generated by Django 5.2.7 on 2025-11-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_column_board'),
        ('card', '0008_card_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='board.column'),
            preserve_default=False,
        ),
    ]
