# Generated by Django 5.2.8 on 2025-12-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
